### ISSUE TITLE
Feature Request: Tutorial on Button and Phototransistor

### ISSUE THREAD

**Issue by BrookeDot** [mrjohnk/TinyGlo2#2]
I've been trying to use the onboard Phototransistor and having some trouble. It would be great if this could be documented somewhere. Currently I'm trying to use this:

```
#define LIGHT A9
void setup() {}
void loop(){
  int r=analogRead(LIGHT);
  DigiKeyboard.println(r);
}
```

The sensor is returning 0. From what I can tell with this microconroller we need to use the analog port number instead of the pin number. I can't tell from the Pinout but it appears that the Phototransistor shares a pin with either 5 or 9.

**Comment by mrjohnk** [comment]
I think the only thing you are missing is a pullup value on the pin that
feeds the button and phototransistor.  Try this example:

#include "DigiKeyboard.h"

#define PHOTO A9
#define PullUP 5

void setup() {
  pinMode(PullUP, INPUT_PULLUP);
}

void loop(){
  int r=analogRead(PHOTO);
  DigiKeyboard.println(r);
  delay(250);
}

**Comment by BrookeDot** [comment]
That did it thanks for the assist! I saw the resistor in the schematic but wasn't sure what to make of it.
