### ISSUE TITLE
Feature Request: Tutorial on Serial COM with TinyGlo+

### ISSUE THREAD

**Issue by guilhermefarto** [mrjohnk/TinyGlo2#3]
Hi.
I would like to know if is possible to use TinyGlo as a Serial COM port.
Dislike an Arduino UNO that is displayed as a Serial COM port, I cannot see what COM port the TinyGlo board is using when connected.
I'm asking this because I need to send and receive data to/from TinyGlo by USB and Java rxtx.jar library.
All the best,

**Comment by mrjohnk** [comment]
I suspect you can communicate with TinyGlo+ over the COM port that is
there.  You will probably need to use a TTL conversion dongle that will
properly convert the signals.  While I have not personally tried it,
something like this product from Adafuit may make this possible:
https://www.adafruit.com/products/70

**Comment by guilhermefarto** [comment]
Hello!
Thanks for answering. I'll try. :)
All the best,
