### ISSUE TITLE
Unable to upload sketches

### ISSUE THREAD

**Issue by JaronrH** [mrjohnk/TinyGlo2#5]
Do you have any more resources on how to get the TinyGlo+ to work with Windows 10 (Arduino 1.6.10 IDE)?  I've followed the directions, installed the driver, and get everything to build but can never get past the "Please plug in the device" stage.  Windows never detects the TinyGlo+'s Digispark bootloader in the first 5s so I can't upload any custom sketches!  Any pointers would be greatly appreciated!  Thanks! (Backer #15)

**Comment by mrjohnk** [comment]
Take a look at the Windows 10 special installation instructions on the page
linked below.  Micronucleus is the bootloader software on the TinyGlo+ that
interfaces with the driver on the computer

https://github.com/micronucleus/micronucleus

**Comment by JaronrH** [comment]
Thanks for the reply!  I tried the zadig installation on my windows 10 machines but it unfortunately didn't help either one.

**Comment by mrjohnk** [comment]
Wish I had better suggestions for you.  I don't have any Windows 10
experience.  I stuck with Windows 7.  Maybe try checking out suggestions
that people have for a similar situation when using the Digispark line of
products on the Digistump forums.

**Comment by JaronrH** [comment]
As much as I hate to admit it, I found the issue... I had the right drivers - what I didn't have was a fully functional USB cable!  Apparently the cable I had quit working at some point.  As soon as I switched to a different cable, everything worked fine.
